sudo: required
services:
    - docker
before_install:
    - docker build -t arunraj17/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true arunraj17/docker-react npm run test
    # - docker run -e CI=true arunraj17/docker-react npm run test -- --coverage